[package]
name = "terminal_view"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/terminal_view.rs"

[features]
test-support = []

[dependencies]
gpui.workspace = true
theme_core.workspace = true
alacritty_terminal.workspace = true
futures.workspace = true
i18n.workspace = true
ui.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
