[package]
name = "acp_client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/acp_client.rs"

[dependencies]
paths.workspace = true
anyhow.workspace = true
agent-client-protocol.workspace = true
serde_json.workspace = true
blocking.workspace = true
futures.workspace = true
host.workspace = true
async-io.workspace = true
