[package]
name = "host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/host.rs"

[[bin]]
name = "necoder-remote-server"
path = "src/bin/remote_server.rs"

[dependencies]
anyhow.workspace = true
ignore.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
