[package]
name = "settings"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/settings.rs"

[dependencies]
acp_client.workspace = true
anyhow.workspace = true
cli_shim.workspace = true
gpui.workspace = true
i18n.workspace = true
settings_core.workspace = true
serde_json.workspace = true
theme_core.workspace = true
